#!/bin/sh
{
    sed 's/#.*//' | sed '/^$/d' |
    while read line; do
        printf "%s\n" "$line"
        printf '\033[1m%s\033[m\n' "$line" >&2
	done | ./pdns-ldap.py | sed -r '/^(END|FAIL)$/a\
'
} <<EOF
HELO	1
Q	tuna.tsinghua.edu.cn	IN	NS	-1	0.0.0.0
Q	ftp4.tuna.tsinghua.edu.cn	IN	A	-1	0.0.0.0
Q	ftp4.tuna.tsinghua.edu.cn	IN	A	-1	59.66.133.1
Q	ftp4.tuna.tsinghua.edu.cn	IN	ANY	-1	0.0.0.0
Q	ftp4.4.tuna.tsinghua.edu.cn	IN	ANY	-1	0.0.0.0
Q	ftp4.6.tuna.tsinghua.edu.cn	IN	ANY	-1	0.0.0.0
Q	mirrors.tuna.tsinghua.edu.cn	IN	A	-1	0.0.0.0
Q	dns.tuna.tsinghua.edu.cn	IN	A	-1	0.0.0.0
Q	tuna.tsinghua.edu.cn	IN	NS	-1	0.0.0.0
Q	tuna.tsinghua.edu.cn	IN	SOA	-1	0.0.0.0
EOF
# vi: noet:
