#!/bin/sh
{
    sed 's/#.*//' | sed '/^$/d' |
    while read line; do
        printf "%s\n" "$line"
        printf '\033[1m%s\033[m\n' "$line" >&2
    done | ./pdns-ldap | sed -r '/^(END|FAIL)$/a\
'
} <<EOF
HELO	1
Q	tuna.tsinghua.edu.cn	IN	NS	-1	0.0.0.0
Q	mirrors.tuna.tsinghua.edu.cn	IN	A	-1	0.0.0.0
Q	mirrors.tuna.tsinghua.edu.cn	IN	ANY	-1	114.231.213.2
Q	mirrors.tuna.tsinghua.edu.cn	IN	ANY	-1	166.111.28.1
Q	mirror.edu.cn	IN	A	-1	0.0.0.0
Q	mirror.edu.cn	IN	A	-1	166.111.28.1
Q	ustc.mirror.edu.cn	IN	CNAME	-1	166.111.28.1
Q	tuna.mirror.edu.cn	IN	A	-1	166.111.28.1
Q	dns.tuna.tsinghua.edu.cn	IN	A	-1	0.0.0.0
Q	tuna.tsinghua.edu.cn	IN	NS	-1	0.0.0.0
Q	tuna.tsinghua.edu.cn	IN	SOA	-1	0.0.0.0
EOF
# vi: noet:
